name: Generate documentation
on: 
  push:
    branches: [ stable ]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Register Problem Matcher
        run: echo "##[add-matcher].github/tsc.json"

      - name: Run TypeScript compiler
        run: npm run build

      - name: Build docs
        run: npm run docs

      - name: Commit docs
        run: |
          git config --global user.name 'xiboon'
          git config --global user.email '38988733+xiboon@users.noreply.github.com'
          git add docs
          git commit -am "docs: create documentaton"
          git push